name: ansible-ryanjyoder # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
#ansible             ansible-doc         ansible-pull ansible-config      ansible-galaxy      ansible-test ansible-connection  ansible-inventory   ansible-vault ansible-console     ansible-playbook  ansible-pull
  ansible-playbook:
    command: bin/snapcraft-preload $SNAP/usr/bin/python3 $SNAP/bin/ansible-playbook
    environment:
      ANSIBLE_CONFIG: $SNAP_USER_DATA/ansible.cfg
      DEFAULT_LOCAL_TMP: $SNAP_USER_DATA/tmp
    plugs: [network, network-bind, home, mount-observe, ssh-keys]

parts:
  ansible:
    plugin: python
    source: https://github.com/ansible/ansible.git
    source-branch: devel
    stage-packages: [git, ssh-client]
    build-packages: [build-essential, libssl-dev, python-dev, libffi-dev]

  snapcraft-preload:
    source: https://github.com/diddlesnaps/snapcraft-preload.git
    source-branch: semaphore-support
    plugin: cmake
    stage-packages:
      - try:
        - lib32gcc1
        - lib32stdc++6
        - libc6-i386
    build-packages:
      - gcc-multilib
      - g++-multilib
